services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  golang:
    container_name: golang_container
    build:
      dockerfile: Dockerfile.local
    environment:
      - STAGE=${STAGE}
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - DD_AGENT_HOST=${DD_AGENT_HOST}
      - S3_BUCKET=${S3_BUCKET}
    ports:
      - 8080:8080
    depends_on:
      - prometheus
    restart: on-failure
    volumes:
      - ./:/app

volumes:
  db:
    driver: local
