services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    restart: on-failure
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - grafana-storage:/var/lib/grafana

  postgres:
    container_name: postgres_container
    image: postgres:13.5
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: turbo_deploy
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "3030:80"
    depends_on:
      - postgres

  golang:
    container_name: golang_container
    build:
      dockerfile: Dockerfile.local
    environment:
      - STAGE=${STAGE}
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - DD_AGENT_HOST=${DD_AGENT_HOST}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TaskDefinitionSubnet1=${TaskDefinitionSubnet1}
      - TaskDefinitionSubnet2=${TaskDefinitionSubnet2}
      - TaskDefinitionSubnet3=${TaskDefinitionSubnet3}
      - TaskDefinitionS3BucketName=${TaskDefinitionS3BucketName}
      - TaskDefinitionSecurityGroup1=${TaskDefinitionSecurityGroup1}
      - ClusterARN=${ClusterARN}
      - TaskDefinitionARN=${TaskDefinitionARN}
      - LOG_QUEUE_URL=${LOG_QUEUE_URL}
      - STATUS_QUEUE_URL=${STATUS_QUEUE_URL}
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - redis
      - grafana
      - postgres
      - prometheus
    volumes:
      - ./:/app

volumes:
  redis-data: {}
  grafana-storage: {}
  db:
    driver: local
