services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  golang:
    container_name: golang_container
    build:
      dockerfile: Dockerfile.local
    environment:
      - STAGE=${STAGE}
      - DB_URL=${DB_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SENTRY_DSN=${SENTRY_DSN}
      - DD_AGENT_HOST=${DD_AGENT_HOST}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - TaskDefinitionSubnet1=${TaskDefinitionSubnet1}
      - TaskDefinitionSubnet2=${TaskDefinitionSubnet2}
      - TaskDefinitionSubnet3=${TaskDefinitionSubnet3}
      - TaskDefinitionS3BucketName=${TaskDefinitionS3BucketName}
      - TaskDefinitionSecurityGroup1=${TaskDefinitionSecurityGroup1}
      - ClusterARN=${ClusterARN}
      - TaskDefinitionARN=${TaskDefinitionARN}
      - LOGS_SQS_URL=${LOGS_SQS_URL}
      - STATUS_SQS_URL=${STATUS_SQS_URL}
    ports:
      - 8080:8080
    depends_on:
      - prometheus
    restart: on-failure
    volumes:
      - ./:/app

volumes:
  db:
    driver: local
