services:
  golang:
    container_name: golang_container_logs_sqs
    build:
      dockerfile: Dockerfile
    environment:
      - STAGE=${STAGE}
      - DB_URL=${DB_URL}
      - AWS_SQS_URL=${AWS_SQS_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: on-failure